---
name: metube
description: Metube is a web frontend for yt-dlp
version: "0.1.0"
slug: metube
url: https://github.com/alexta69/metube
init: false
description: Metube is a web frontend for yt-dlp
webui: http://[HOST]:[PORT:8081]
arch:
  - aarch64
  - amd64
ports:
  8081/tcp: 8081
